### ISSUE TITLE
more comments on final draft

### ISSUE THREAD

**Issue by beanumber** [ambertin/thesis#11]
- pg. 76:
    - Put journal titles in *italics* everywhere
    - "...could also ~~see~~ benefit~~s~~..."
- pg. 77:
    - "...it would save..." -> "...it could save..."
    - The sentence starting "Some schools prioritize..." is too long. Please break it up into multiple sentences. 
    - "[Alt]hough..." -- generally there is never a reason to start a sentence with "though". Just use "although". 
- pg. 79:
    - "At the beginning of their course~~s~~..."
- pg. 81:
    - "[Alt]hough certainly not..." 
    - Be consistent with the spelling of "RStudio"
- pg. 87:
    - There is a LaTeX parse error where you have `Overall_Total Group`. Use `$Overall_{Total}$` if you want more than one character to be in the subscript. 
- pg. 91:
    - "For the control[,] group..." -- remove comma
- pg. 93:
    - "impelled" -> "compelled"
- pg. 94:
    - "[T]here is the additional limitation that[,] although..." -- remove "Then" and comma
- References:
    - Please review the references quickly for consistency. Every reference should have a year and author.  
    - "10 American Economic Association" -- can you find an author? What's the 10 for? 
    - Baumer, Cetinkaya-Rundel: the reference is still duplicated. Please also use the TISE version of the paper. https://escholarship.org/uc/item/90b2f5xh
    - Eisner -- check the URL; it looks like the DOI and the URL have run together. If you have the DOI, use the `doi` field in BibTeX. 
    - Horton, Baumer, Wickham: Please use the CHANCE version: https://www.tandfonline.com/doi/abs/10.1080/09332480.2015.1042739
    - Hrynasziewicz: again, the DOI and URL appear to have run together
    - Marwick, Boettinger: the URL is wrong ("doi.org" is repeated twice)

**Comment by ambertin** [comment]
Fixed these all in 275715f, plus lots more edits to the bib file to make everything consistent and ensure that everything that should have a link had one.

The weird 10 popping up seems to be not related to that specific citation and rather a weird bug with the template (I edited to have another citation come up first and it _also_ had the 10 show up (when it didn't have it in its original spot).

Will try to figure out what's going on there if I can, will close this issue for now (and keep that in my mind elsewhere) since everything else is good to go!
